### PR TITLE
Fujx/go mod

### PR DESCRIPTION
**Pull request by bill828**
This change is for issue #6 .

Uses `go mod` instead of `dep`.

### CODE REVIEW

**Comment by dingwenfang** [comment]
Could you explain a bit for the vendor directory changes? Will the vendor directory be honored by go build after the change?

**Comment by dingwenfang** [comment]
Is the go version we support changed? We might need to update document if changed.

**Comment by bill828** [comment]
> Could you explain a bit for the vendor directory changes? Will the vendor directory be honored by go build after the change?

directory "vendor" was updated by "go mod vendor". The directory will not be changed after building.

**Comment by bill828** [comment]
> Is the go version we support changed? We might need to update document if changed.

Yes, the go version should be 1.13. I have updated the documents.

**Comment by dingwenfang** [comment]
Do we need to use 'go build -mod=vendor' to use the vendor directory for dependencies?

**Comment by bill828** [comment]
> Do we need to use 'go build -mod=vendor' to use the vendor directory for dependencies?

We need to run `go mod vendor` to update folder `vendor` only when `go.mod` gets changed, for example, a new 3rd library gets involved.

**Pull request merged**
